module.exports = {
  trailingSlash: true,
  env: {
    STORYBLOK_ACCESS_TOKEN: process.env.STORYBLOK_ACCESS_TOKEN,
    BASE_URL: process.env.BASE_URL,
    API_BASE_URL: process.env.API_BASE_URL,
    THIRDWEB_API_KEY: process.env.THIRDWEB_API_KEY,
    WALLETCONNECT_PROJECT_ID: process.env.WALLETCONNECT_PROJECT_ID,
    ONRAMPER_API_KEY: process.env.ONRAMPER_API_KEY,
    PALOMA_EXTENSION_ID: process.env.PALOMA_EXTENSION_ID,
    PALOMA_NEST_SERVICE_API_BASE_URL: process.env.PALOMA_NEST_SERVICE_API_BASE_URL,
  },
};

